version: "3.4"

services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=example --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
