POST https://localhost:5001/donate HTTP/1.1
content-type: application/json

{
    "encryptedAnswers":"S2bnG/7halV6ayM+HAWtbaacX3Bd4Qt914WuSQpHwQ==",
    "encryptedKey":"zvx8+1ryl/YTkp/vizz1x2NHyVksCsclygpl3CA8OvnQonRGXxnP8UjVZ1qQNsLt1Th+Bt49vbwqy64rwQ5VYTB19/riFJZWRI3t6rSlCbnhpejI2sS04lbuOHT6cCv8Cbb8NRYe0/ETFiywFRA3NePeBkNppWmx4Yod75arlpHxUeKGmuU7litkW0D6KQRJH/uUjQL9aTqTB2J2nXXii4RTUlwHP2Kle7rnB8FvSct5NjOSyVFeUpsYULbHWpfoT8yeZ/e0jp6Yx0JgLfygbKWOQNLjxjovlFktMBIsry6KfCURZ2Tr+nHvMZgO4hLlsoC0HbRfIPUtEEsEPIIVxQ==",
    "iv":"4P62rnXAZbh0gfTv",
    "signingKey":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1O2IB+zQH01J6MW+ZpyH/lENnr1ny9et\nGHi7H2xvo/l4yeJXIQg0H8rJfp59wxtEL0YnOzB9SFByNEwoDsd7D03PvLOhth6605Yp9Tk2mTxf\n9YFdXD+voWhjInvl+2X+Ny8OUctdOS1P/3GOBn4+AHBd6QCyMxRUljOx7khzTkWckPafk6Ft9k1W\nzkVso0ID+Yr553g4VOn8UBIYP/61x5GP/WlWvUnKnQw5x+gXEYEBW0uJ5zNqkh/AB851SWsWCoPz\nD2PiHKGrUygRVSzjZa1fJhP+fa/29SxWnH6IiEmrVXHyTYkZ4gVYTLX31cKv6yM9w4BcgCe2Gy65\nvyP63QIDAQAB\n-----END PUBLIC KEY-----"
}

