# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Update GIF

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - tests-bats/demo.tape

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - name: Install Deps
      run: | 
        cd ..
        sudo apt-get update
        sudo apt-get install ffmpeg build-essential cmake git libjson-c-dev libwebsockets-dev -y
        git clone https://github.com/tsl0922/ttyd.git
        cd ttyd && mkdir build && cd build
        cmake ..
        make && sudo make install
        go install github.com/charmbracelet/vhs@latest

    - name: Run Generator
      run: |
        cd tests-bats
        npx bats decrypt-tool.bats --filter 'generategif'

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: | 
          Update demo.gif

          SKIP_CI
        file_pattern: 'docs/demo.gif'


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: api
        # A file, directory or wildcard pattern that describes what to upload
        path: docs/demo.gif
        if-no-files-found: error
